/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_glfw_ImGuiGLFW */

#ifndef _Included_imgui_glfw_ImGuiGLFW
#define _Included_imgui_glfw_ImGuiGLFW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_glfw_ImGuiGLFW
 * Method:    init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_glfw_ImGuiGLFW_init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_glfw_ImGuiGLFW
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_glfw_ImGuiGLFW_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     imgui_glfw_ImGuiGLFW
 * Method:    newFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imgui_glfw_ImGuiGLFW_newFrame
  (JNIEnv *, jclass);

/*
 * Class:     imgui_glfw_ImGuiGLFW
 * Method:    installCallbacks
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_glfw_ImGuiGLFW_installCallbacks
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_glfw_ImGuiGLFW
 * Method:    restoreCallbacks
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_glfw_ImGuiGLFW_restoreCallbacks
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
